helpcenter/urls.py
'''Generic module doc-string.'''
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('home', views.redirect_home, name='redirect_home'),
    path('about', views.about, name='about'),
    path("tickets/", views.tickets, name="tickets"),
    path("tickets/create", views.create, name="create"),
    path("tickets/all", views.list, name="list"),
    path("login", views.login_user, name="login"),
    path("register_user", views.register_user, name="register_user"),
    path("logout_user", views.logout_user, name="logout"),
    path("tickets/edit/<int:ticket_id>", views.edit_ticket, name="edit_ticket"),
    path("delete_ticket/<int:ticket_id>", views.delete_ticket, name="delete-ticket"),
    path('tickets/edit/status/<int:ticket_id>/', views.edit_ticket_status, name='edit_ticket_status'),
]


handler404 = 'helpcenter.views.redirect_to_homepage'

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('helpcenter.urls')),
    # path("login/", include("django.contrib.auth.urls"))
]

helpcenter/models.py
'''Module Doctstring Goes Here.'''
import uuid
from django.conf import settings
from django.db import models
from django.utils import timezone

class Ticket(models.Model):
    '''Defines the data fields and parameters of our tickets.'''

    # The "id" field-- a unique, randomly generated, value.
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4,serialize=True, editable=False)
    id = models.AutoField(primary_key=True)
    # The "author" field-- the username of whomever created the ticket.
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='posts'
        )
    # The "title" field-- a brief summary of the subject to follow.
    title = models.CharField(max_length=200)
    last_updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    # The "subject" field-- a detailed description of the above-mentioned title.
    subject = models.TextField()
    # The "submitted_date" field-- a timestamp of the ticket creation date.
    # submitted_date = models.DateTimeField(blank=True, null=True, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    # The "status" field-- tracks the support status of the ticket. (not implemented)
    class Status(models.IntegerChoices):
        '''Enum setup for the status field.'''
        PENDING = 0
        ACTIVE  = 1
        CLOSED  = 2

    status = models.IntegerField(default=0,choices=Status.choices)

    def publish(self):
        '''This is called whenever the user hits the "save" button in the webapp.'''
        self.submitted_date = timezone.now()
        self.save()

    def __str__(self):
        '''Generic function doc-string'''
        # pylint: disable=invalid-str-returned

        return self.title
    

helpcenter/forms.py
from django import forms
from .models import Ticket

class EditTicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['title', 'subject']


class EditTicketStatusForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['status']

helpcenter/views.py
'''Generic module doc-string.'''
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import UpdateView
from .models import Ticket
from .forms import EditTicketForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse
from .forms import EditTicketStatusForm

# Create your views here.

def home(request):
    '''This is our homepage!'''
    return render(request, 'helpcenter/home.html', {})

def tickets(request):
    # Check if the user is authenticated (logged in)
    if request.user.is_authenticated:
        # Get all posts by the currently logged-in user
        user_tickets = request.user.posts.all().order_by('-created_at')
    else:
        user_tickets = []  # Return an empty list if the user is not logged in

    return render(request, 'helpcenter/tickets.html', {'user_tickets': user_tickets})


@login_required
def create(request):
    if request.method == "POST":
        
        ticket_title = request.POST['title']
        subject = request.POST['subject']

        if request.user.is_authenticated:
            new_ticket = Ticket(title=ticket_title, subject=subject, author=request.user)
            new_ticket.save()
            messages.success(request, "Ticket Added Successfully")
        else:
            messages.error(request, "Login to create a ticket.")

        return redirect("home")
    else:
        return render(request, 'helpcenter/create.html', {})


def about(request):

    return render(request, 'helpcenter/about.html', {})

def list(request):

    if request.user.is_staff:
        user_tickets = Ticket.objects.all().order_by('-created_at')
    else:
        user_tickets = [] 

    return render(request, 'helpcenter/list.html', {'user_tickets': user_tickets})





def login_user(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("home")
        else:
            messages.success(request, ("There was an Error"))
            return redirect("login")
    else:
        return render(request, 'helpcenter/login.html', {})


def register_user(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password1"]
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect("home")
        else:
            form = UserCreationForm()
    else:
        form = UserCreationForm()
    return render(request, "helpcenter/register_user.html", {'form' :form,})

def redirect_home(request):
     return redirect('home')

def logout_user(request):
    logout(request)
    messages.success(request, ("Logged Out.."))
    return redirect("home")


@login_required
def edit_ticket(request, ticket_id):

    ticket = get_object_or_404(Ticket, pk=ticket_id)

    if request.user != ticket.author:
        messages.error(request, "No Permission")
        return HttpResponseRedirect(reverse('tickets'))

    if request.method == "POST":
        form = EditTicketForm(request.POST, instance=ticket)
        if form.is_valid():
            form.save()
            messages.success(request, "Ticket Updated")
            return HttpResponseRedirect(reverse('tickets'))
    else:
        form = EditTicketForm(instance=ticket)

    return render(request, 'helpcenter/edit_ticket.html', {'form': form, 'ticket': ticket})



@login_required
def delete_ticket(request, ticket_id):
    referer_url = request.META.get('HTTP_REFERER')
    del_ticket = Ticket.objects.get(pk=ticket_id)
    del_ticket.delete()
    messages.success(request, ("Ticket Deleted"))
    return redirect(referer_url or 'default_page_name')


def update_ticket_status(request):
    if request.method == "POST":
    
        ticket_id = request.POST.get('ticket_id')
        new_status = request.POST.get("status")

        return JsonResponse({"status": "success"})
    else:
        return JsonResponse({"status": "error"})
    
def edit_ticket_status(request, ticket_id):
    ticket = get_object_or_404(Ticket, id=ticket_id)
    if request.user.is_staff:
        if request.method == 'POST':
            form = EditTicketStatusForm(request.POST, instance=ticket)
            if form.is_valid():
                form.save()
                return redirect("list")
        else:
            form = EditTicketStatusForm(instance=ticket)

        return render(request, 'helpcenter/edit_ticket_status.html', {'form': form})
    
    return redirect("home")


def redirect_to_homepage(request, exception):
    return redirect('home')

helpcenter/templates/helpcenter/about.html
{% extends 'helpcenter/base_layout.html' %} {% block content %} {% endblock %}

helpcenter/templates/helpcenter/base_layout.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Support Center</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'helpcenter-css/main.css' %}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'helpcenter-css/custom.css' %}"
    />
    <link
      href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext"
      rel="stylesheet"
      type="text/css"
    />
  </head>
  <body>
    <nav
      class="navbar navbar-expand-sm navbar-dark"
      style="background-color: #9a29c7"
    >
      <a href="\home" class="navbar-brand mb-0 h1">Support Center</a>
      <button
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarNav"
        class="navbar-toggler"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        Menu
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a href="\home" class="nav-link active">Home</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a href="\register_user" class="nav-link active">Register</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'login' %}" class="nav-link active">Login</a>
          </li>
          {% endif %}

          <!-- <li class="nav-item">
            <a href="\about" class="nav-link active">About</a>
          </li> -->
        </ul>
      </div>
    </nav>
    <div class="wrapper">{% block content %} {% endblock %}</div>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
</html>

helpcenter/templates/helpcenter/create.html
{% extends 'helpcenter/base_layout.html' %} {% block content %}
<div class="create-page">
  <h1 class="text-center support-portal ticket-form">Ticket Form</h1>
  <form action="" method="POST">
    {% csrf_token %}
    <div class="form-group">
      <label for="exampleFormControlTextarea1">Title</label>
      <textarea
        class="form-control ticket-title"
        id="exampleFormControlTextarea1"
        rows="1"
        name="title"
        required
      ></textarea>
    </div>

    <div class="form-group ticket-group">
      <label for="exampleFormControlTextarea1">Subject</label>
      <textarea
        class="form-control ticket-information"
        id="exampleFormControlTextarea1"
        rows="3"
        name="subject"
        required
      ></textarea>

      <button type="submit" class="btn btn-info submit-ticket-btn">
        Submit Ticket
      </button>
    </div>
  </form>
</div>
{% endblock %}

helpcenter/templates/helpcenter/edit_ticket.html
{% extends 'helpcenter/base_layout.html' %} {% block content %}
<h1 class="text-center support-portal ticket-form">Edit Ticket</h1>
<div class="center-container">
  <div class="ticket-form-container">
    <form method="post">
      <div class="edit-form">{% csrf_token %} {{ form.as_p }}</div>
      <button type="submit" class="btn btn-info submit-ticket-btn">
        Update Ticket
      </button>
    </form>
  </div>
</div>
{% endblock %}

helpcenter/templates/helpcenter/edit_ticket_status.html
{% extends 'helpcenter/base_layout.html' %} {% block content %}
<h1 class="text-center support-portal ticket-form">Update Ticket Status</h1>
<div class="center-container">
  <div class="ticket-form-container">
    <form method="post">
      <div class="edit-form">{% csrf_token %} {{ form.as_p }}</div>
      <button type="submit" class="btn btn-info submit-ticket-btn">
        Update Status
      </button>
    </form>
  </div>
</div>
{% endblock %}

helpcenter/templates/helpcenter/home.html
{% extends 'helpcenter/base_layout.html' %}
{% block content %}
    {% if user.is_authenticated %}
    <h1 class="text-center support-portal">Group 2 Support Portal</h1>
    <h1 class="welcome-alert">Welcome, {{ user }}</h1>
    {% endif %} {% if user.is_authenticated %}
    <hr class="home-hr">
   
    {% for msg in messages %}
    <div class="alert-container">
    <div class="alert alert-success alert-dismissible fade show text-center" role="alert">
      <strong>{{ msg }}</strong>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
    {% endfor %}
    <div class="flex-container-home">
      <div class="flex-item flex-item1">
      <article class="container">
         

      

      <h2><a href="\tickets\create" class="ticket-home-link">Create a Ticket!</a></h2>
      <small>Create a ticket here.</small>   
      {% if user.is_staff %}
      <h2><a href="\tickets\">View/edit your tickets</a></h2>
      <small>Review your existing tickets here!</small>

      <h2><a href="\tickets\all" class="staff-home-link">View all tickets</a></h2>
      <small>Review all existing tickets here!</small>

      {% else %}

      <h2><a href="\tickets">View/Edit Your Tickets</a></h2>
      <small>Review your existing tickets here!</small>

      {% endif %}
    </article>
  </div>
  <div class="flex-item flex-item2 flex-image-home">&nbsp;</div>
  </div>

    {% if user.is_staff %}






    

    <!-- Section of site for users not logged in -->
    {% endif %} {% endif %} {% if user.is_authenticated == False %}
    {% for msg in messages %}
    <div class="alert-container alert-right">
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <strong>{{ msg }}</strong>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
    {% endfor %}
    <container class="welcome-info">
      <h2>Group 2's Support Center</h2>
      <div class="home-image">&nbsp;</div>
      <p class="welcome-text">
        Welcome to Group 2's Support Center! Our mission is to provide you with seamless and convenient assistance for all <br>of your tech-related issues.
      </p>

      <container class="btn-container">
        <a class="btn btn-info login-btn" href="\login">Login</a>
        <hr></hr>
        <a class="btn btn-info register-btn" href="\register_user">Register</a>
      </container>
    </container>
    {% endif %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
{% endblock %}

helpcenter/templates/helpcenter/list.html
{% extends 'helpcenter/base_layout.html' %} {% block content %}
<h1 class="text-center support-portal">All User Tickets</h1>

{% for msg in messages %}
<div class="alert-container">
  <div
    class="alert alert-success alert-dismissible fade show text-center"
    role="alert"
  >
    <strong>{{ msg }}</strong>
    <button
      type="button"
      class="btn-close"
      data-bs-dismiss="alert"
      aria-label="Close"
    ></button>
  </div>
</div>
{% endfor %}

<div class="center-container">
  <div class="ticket-container">
    <table>
      <tr>
        {% for post in user_tickets %}
        <td class="{% cycle 'odd-staff' 'even-staff' %}">
          <article>
            <div class="ticket-title-staff">
              <small>Title:</small>
              <h2>{{ post.title }}</h2>
            </div>
            <p class="author">By: {{ post.author }}</p>
            <!-- <p>Created: {{ post.created_at }}</p>
            <p>Last Updated: {{ post.updated_at }}</p> -->
            <hr class="hr-staff" />
            <div>
              <p class="subject-item-staff">Subject:</p>
              <p class="ticket-subject-staff">
                {{ post.subject|linebreaksbr }}
              </p>
            </div>
            <div class="update-info-staff">
              <small>Created: {{ post.created_at }}</small>
              <small>Last Updated: {{ post.updated_at }}</small>
            </div>
            <div class="ticket-btn-container">
              <!-- <label for="status" class="status-lbl">Status:</label> -->
              <a
                href="{% url 'edit_ticket_status' ticket_id=post.id %}"
                class="ticket-btn btn btn-info edit-status-btn edit-status-btn update-status-btn"
                >Change Status</a
              >
              <a
                class="{% if post.status == 0 %}status-pending{% elif post.status == 1 %}status-active{% else %}status-closed{% endif %} status-font"
                >Status: {{ post.get_status_display }}</a
              >
              <a
                href="{% url 'delete-ticket' ticket_id=post.id %}"
                class="ticket-btn btn btn-info delete-btn"
                >Delete</a
              >
            </div>
          </article>
        </td>
        {% endfor %}
      </tr>
    </table>
  </div>
</div>
{% if not user_tickets %}
<p class="text-center no-tickets">No tickets available.</p>
{% endif %} {% endblock %}

helpcenter/templates/helpcenter/login.html
{% extends 'helpcenter/base_layout.html' %} {% block content %}
<div class="login-page">
  <h2>User Log In</h2>
  <form method="post">
    {% csrf_token %}
    <div class="login-forms">
      <div class="form-group">
        <label for="exampleInputEmail1">Username</label>
        <input type="text" class="form-control" name="username" />
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" class="form-control" name="password" />
      </div>
    </div>

    <div class="text-center">
      <button type="submit" class="btn btn-info login-page-btn">Log In</button>
    </div>
  </form>
</div>
{% endblock %}

helpcenter/templates/helpcenter/register_user.html
{% extends 'helpcenter/base_layout.html' %} {% block content %}
<div class="register-page">
  <h2>Register</h2>
  <div class="register-form">
    <form action="{% url 'register_user' %}" method="POST">
      {% csrf_token %} {{ form.as_p }}
      <div class="text-center">
        <button type="submit" class="btn btn-info login-page-btn">
          Register
        </button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

helpcenter/templates/helpcenter/tickets.html
{% extends 'helpcenter/base_layout.html' %} {% block content %}
<h1 class="text-center support-portal">Your Tickets</h1>
{% for msg in messages %}
<div class="alert-container">
  <div
    class="alert alert-success alert-dismissible fade show text-center"
    role="alert"
  >
    <strong>{{ msg }}</strong>
    <button
      type="button"
      class="btn-close"
      data-bs-dismiss="alert"
      aria-label="Close"
    ></button>
  </div>
</div>
{% endfor %}

<div class="center-container">
  <div class="ticket-container">
    <table>
      <tr>
        {% for post in user_tickets %}
        <td class="{% cycle 'odd' 'even' %}">
          <article>
            <div class="ticket-title">
              <small>Title:</small>
              <h2>{{ post.title }}</h2>
            </div>

            <hr />
            <div>
              <p class="subject-item">Subject:</p>
              <p class="ticket-subject">{{ post.subject|linebreaksbr }}</p>
            </div>
            <div class="update-info">
              <small>Created: {{ post.created_at }}</small>
              <small>Last Updated: {{ post.updated_at }}</small>
            </div>
            <div class="ticket-btn-container">
              <a
                href="{% url 'edit_ticket' ticket_id=post.id %}"
                class="ticket-btn btn btn-info edit-status-btn edit-status-btn"
                >Edit</a
              >
              <a
                class="{% if post.status == 0 %}status-pending{% elif post.status == 1 %}status-active{% else %}status-closed{% endif %} status-font"
                >Status: {{ post.get_status_display }}</a
              >
              <a
                href="{% url 'delete-ticket' ticket_id=post.id %}"
                class="ticket-btn btn btn-info delete-btn"
                >Delete</a
              >
            </div>
          </article>
        </td>
        {% endfor %}
      </tr>
    </table>
  </div>
</div>

{% if not user_tickets %}
<p class="text-center no-tickets">No tickets available.</p>

{% endif %} {% endblock %}